fixup! kernel requirements at matrix level 6, Kernel config errors
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
For config CONFIG_ANDROID_PARANOID_NETWORK, value = y but required n
    Missing config CONFIG_CRYPTO_CHACHA20POLY1305
    Missing config CONFIG_SONY_FF
    Missing config CONFIG_TRACE_GPU_MEM
    Missing config CONFIG_XFRM_MIGRATE
: Success
INCOMPATIBLE